globals:
  debug: true
  id: not_used
  name: intel471_collector
  persistence:
    type: filesystem
    config:
      directory_name: state
#    type: redis
#    config:
#      host: host
#      port: port
#      password: password
#      db: db

outputs:
#  devo_1:
#    type: devo_platform
#    config:
#      address: collector-us.devo.io
#      port: 443
#      type: SSL
#      chain: chain.crt
#      cert: <devo_domain>.crt
#      key: <devo_domain>.key
#  devo_2:
#    type: devo_platform
#    config:
#      address: collector-eu.devo.io
#      port: 443
#      type: SSL
#      chain: chain.crt
#      cert: <devo_domain>.crt
#      key: <devo_domain>.key
#  relay_1:
#    type: syslog
#    config:
#      address: 127.0.0.1
#      port: 13000
#      period_sender_stats_in_seconds: 60
#      concurrent_connections: 2
  # console_1:
  #   type: console

inputs:
  intel471_input:
    id: 1
    enabled: true
    credentials:
      username:
      password:
    environment: prod
    parameters:
      duration: 30  # n days of indicators to collect
    requests_limits:
      - period: 1d
        number_of_requests: -1
      - period: 1h
        number_of_requests: -1
      - period: 1m
        number_of_requests: -1
      - period: 1s
        number_of_requests: -1
    services:
      indicators_service:
